### ISSUE TITLE
Talon 6.0

### ISSUE THREAD

**Issue by klinker24** [klinker24/talon-for-twitter-android#53]
I want to revamp some things for Android 6.0 and optimize Talon further.

* [x] Use [ChipCloud](https://github.com/fiskurgit/ChipCloud) to create a filter for a "profile timeline". Chips for: tweets, replies, retweets, mentions, quotes, and likes.
  * [x] Sort all the tweets by time
  * [x] Load 20 tweets directly on the profile page
  * [x] Have a "Show All" button at the bottom, just like the `TweetActivity`
* [x] Conversation for a tweet (#56)
  * [x] Change the replies at the top of the tweet activity to match the new style of threads
* [x] #60 for improving the UI of quoted tweets
* [x] Tapping tweets will open them in the tweet viewer, always
  * [x] Long clicking should just show the number of likes and retweets, instead of everything
  * [x] Long clicking should show the reply, like, quote, and retweet buttons
* [x] Revamp the profile UI
  * [x] drag dismiss layout
  * [x] Use a header similar to the article layout
  * [x] Condense all the meta-data on the profile a bit more
  * [x] Add a FAB to the drag dismiss content layout to compose
  * [x] Be able to see the user's lists on their profile (#47)
* [x] Revamp the tweet viewer
  * [x] Drag dismiss layout
  * [x] Speed up everything
  * [x] Turn the retweet and like button into text instead. "6 retweet  12 likes"
  * [x] Redo how the buttons work
  * [x] Improve the conversations layout
* [x] Black theme on the article viewer
* [x] Improve the look of quoting tweets in the `ComposeActivity`
* [x] Add option to only show people you follow when composing a tweet
* [x] Use the [ConstraintLayout](https://developer.android.com/training/constraint-layout/index.html) to improve performance on the lists
* [x] Get the previous tweets in the timeline to not push down the current tweet, when opening up the tweet viewer
* [x] Use the drag dismiss layout on the `PhotoViewerDialog`
* [x] Use disk cache strategy: Source
* [x] Default to the blue theme

---

**Promo:**

- [x] New video from [RenderForest](https://renderforest.com)
- [x] Update with new images
- [x] Redo the app description
